sudo: required
dist: trusty
branches:
  only:
    - master
services:
  - docker
before_install:
        - docker pull mbredel/thesis-template:latest 
script:
  - docker run mbredel/thesis-template:latest
