sudo: required
dist: trusty
branches:
  only:
    - master
before_install:
  - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-full
script:
  - pdflatex -interaction=nonstopmode -halt-on-error thesis.tex
  - test -f thesis-blx.bib && ( bibtex thesis; pdflatex thesis.tex ) 
  - pdflatex -interaction=nonstopmode -halt-on-error thesis.tex
